export PYTHONPATH=/home/wangyuhan/MPPI/src:$PYTHONPATH
export MPPI_USE_CUROBO_COLLISION=1
export MPPI_W_SCENE_COLLISION=1
export MPPI_SCENE_FROM_PCD_BACK_CAM=1

export MPPI_SCENE_PCD_SCALE=1
export MPPI_SCENE_PCD_IN_BASE=1

export MPPI_SCENE_ADD_TABLE=1
export MPPI_SCENE_TABLE_DIMS='2.0,2.0,0.2'
export MPPI_SCENE_TABLE_CENTER='0.4,0.0,-0.1'

export MPPI_SCENE_REMOVE_TABLE_POINTS=1
export MPPI_SCENE_TABLE_EPS_M=0.01

export MPPI_SCENE_REMOVE_WALL_POINTS=1
export MPPI_SCENE_WALL_DIMS='2.5,0.5,2.0'
export MPPI_SCENE_WALL_CENTER='0.5,0.5,-0.5'
export MPPI_SCENE_WALL_MARGIN_M=0.05

export MPPI_T_BASE_CAM_BACK_PATH=/home/wangyuhan/MPPI/configs/T_base_cam.yaml
export MPPI_SCENE_ROI_MIN='-0.1,-0.7,-0.05'
export MPPI_SCENE_ROI_MAX='1.2,0.7,1.2'
export MPPI_SCENE_VOXEL_SIZE_M=0.01
export MPPI_SCENE_PADDING_M=0.02
export MPPI_SCENE_MAX_CUBOIDS=20
export MPPI_SCENE_ROBOT_MASK_MARGIN_M=0.2
export MPPI_SCENE_MIN_CLUSTER_VOXELS=20

export MPPI_SCENE_TRACK_ALPHA=0.6
export MPPI_SCENE_TRACK_REMOVE_AFTER_MISSES=5
export MPPI_SCENE_TRACK_MAX_TRACKS=20
export MPPI_SCENE_TRACK_MATCH_CENTER_DIST_M=0.05
export MPPI_SCENE_TRACK_MATCH_IOU_MIN=0.05

export MPPI_INFER_BUDGET_MS=50
export MPPI_BUDGET_MAX_DYNAMIC_CUBOIDS=6

python3 -m mppi.cli server --host 0.0.0.0 --port 9010 --open-loop-horizon 8 --policy mppi_joint